
import static com.sun.xml.internal.bind.marshaller.Messages.format;
import static com.sun.xml.internal.bind.marshaller.Messages.format;
import static com.sun.xml.internal.bind.unmarshaller.Messages.format;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import oracle.net.aso.b;
import static sun.security.jgss.GSSUtil.login;

 
public class Add_Member extends javax.swing.JFrame {
    Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
         
         private String updatedMember;
	 private ImageIcon finalImage;
	 private String filename;
	 private String gender=null;
	 private String contryVal=null;
         
          public Add_Member() {
        initComponents();
    }
         
          public void updating(String idno)
	{
		con=Connect.connectDb();
		 String sql="select * from members where id='"+idno+"'";
                 
	       try {
		    	pst=con.prepareStatement(sql);
		        rs=pst.executeQuery();
		        if(rs.next())
                
		        {
                                  txtId.setText(rs.getString("id"));
                                  
		        	  txtmemberno.setText(rs.getString("membership_no"));
                                  
		        	  txtFullname.setText(rs.getString("full_name"));
		        	  txtEmail.setText(rs.getString("email"));
		        	  txtOccupation.setText(rs.getString("occupation"));
		        	  String rgender=rs.getString("gender");
		        	  if(rgender.equals("Male"))
		        	  {
		        		  rdbtnMale.setSelected(true);
		        		  gender="Male";
		        	  }
		        	  else {
		        		  rdbtnFemale.setSelected(true);
		        		  gender="Female";
		        	  }
		        	 
		        	  txtAddress.setText(rs.getString("address"));
		        	  cmbxStatus.setSelectedItem(rs.getString("status"));
		        	  comboCountry.setSelectedItem(rs.getString("country"));
		        	  txtWeight.setText(rs.getString("weight"));
		        	  startDate.setDate(rs.getDate("start_date"));
		        	  endDate.setDate(rs.getDate("end_date"));
		        	  registeredDate.setDate(rs.getDate("reg_date"));
		        	  cmbxFeesmode.setSelectedItem(rs.getString("fees_mode"));
		        	  txtPaidfee.setText(rs.getString("paid_fee"));
		        	  cmbxDuration.setSelectedItem(rs.getString("duration"));
		        	  txtDiscription.setText(rs.getString("discription"));
		        	  dob.setDate(rs.getDate("dob"));
		        	  textContact.setText(rs.getString("contact_no"));
		        	  byte[] imagebytes = rs.getBytes("img");
		        	  Image image=getToolkit().createImage(imagebytes);
		        	  Image newImage=image.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(),Image.SCALE_SMOOTH);
			    	  ImageIcon icon=new ImageIcon(newImage);		        	 
		        	  lblPhoto.setIcon(icon);
		        	  
		        	  txtOccupation.setText(rs.getString("occupation"));
		        	  
		        	   pst.close();
		    		   rs.close();
		    		   con.close();
					
				
				}
		        
	       }catch(Exception e)
	       {
	    	   JOptionPane.showMessageDialog(null, e);
	       }
	       finally {
	    	   try {
	    		   
	    		   pst.close();
	    		   rs.close();
	    		   con.close();
				
			} catch (Exception e2) {
				JOptionPane.showMessageDialog(null, e2);
			}

               }
}
         
         public void itemStateChanged(ItemEvent arg0) {
				String item=cmbxDuration.getSelectedItem().toString();
				if(item.equals("4"))
					{
					Date d=startDate.getDate();
					int month=d.getMonth();
					month=month+4;
					int day=d.getDay();
					day=day+4;
					d.setMonth(month);
					
					endDate.setDate(d);
					
					}
			}
         
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        txtPaidfee = new javax.swing.JTextField();
        cmbxDuration = new javax.swing.JComboBox<>();
        cmbxStatus = new javax.swing.JComboBox<>();
        txtWeight = new javax.swing.JTextField();
        comboCountry = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        textContact = new javax.swing.JTextField();
        rdbtnFemale = new javax.swing.JRadioButton();
        rdbtnMale = new javax.swing.JRadioButton();
        txtmemberno = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rSButtonHover2 = new rojerusan.RSButtonHover();
        txtDiscription = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbxFeesmode = new javax.swing.JComboBox<>();
        txtAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtOccupation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        registeredDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        rSButtonHover9 = new rojerusan.RSButtonHover();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSave = new rojerusan.RSButtonHover();
        rSButtonHover10 = new rojerusan.RSButtonHover();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblPhoto = new rojerusan.RSLabelImage();
        jPanel1 = new javax.swing.JPanel();
        btnUpload = new rojerusan.RSButtonHover();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fill the Member Details ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPaidfee.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtPaidfee.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(txtPaidfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 170, -1));

        cmbxDuration.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cmbxDuration.setForeground(new java.awt.Color(0, 153, 51));
        cmbxDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbxDuration.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxDurationItemStateChanged(evt);
            }
        });
        jPanel3.add(cmbxDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 170, -1));

        cmbxStatus.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cmbxStatus.setForeground(new java.awt.Color(0, 153, 51));
        cmbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registerd" }));
        jPanel3.add(cmbxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 170, -1));

        txtWeight.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 170, -1));

        comboCountry.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        comboCountry.setForeground(new java.awt.Color(0, 153, 51));
        comboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sri Lanka\t", "India", "Nepal", "Pakistan" }));
        jPanel3.add(comboCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 170, -1));

        dob.setForeground(new java.awt.Color(102, 255, 0));
        dob.setDateFormatString("yyyy-MM-dd");
        dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dobMouseReleased(evt);
            }
        });
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobKeyReleased(evt);
            }
        });
        jPanel3.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 170, 30));

        textContact.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        textContact.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(textContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, -1));

        rdbtnFemale.setBackground(new java.awt.Color(0, 0, 0));
        btnGroup.add(rdbtnFemale);
        rdbtnFemale.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rdbtnFemale.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnFemale.setText("Female");
        rdbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnFemaleActionPerformed(evt);
            }
        });
        jPanel3.add(rdbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        rdbtnMale.setBackground(new java.awt.Color(0, 0, 0));
        btnGroup.add(rdbtnMale);
        rdbtnMale.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rdbtnMale.setForeground(new java.awt.Color(255, 255, 255));
        rdbtnMale.setText("Male");
        rdbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnMaleActionPerformed(evt);
            }
        });
        jPanel3.add(rdbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        txtmemberno.setEditable(false);
        txtmemberno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtmemberno.setForeground(new java.awt.Color(204, 0, 0));
        txtmemberno.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtmembernoComponentShown(evt);
            }
        });
        txtmemberno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmembernoActionPerformed(evt);
            }
        });
        jPanel3.add(txtmemberno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, -1));

        txtFullname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(0, 153, 51));
        txtFullname.setToolTipText("");
        txtFullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFullnameKeyReleased(evt);
            }
        });
        jPanel3.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member No");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact No");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Of Birth");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Country");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Weight");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Duration");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Paid Fee");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        rSButtonHover2.setBackground(new java.awt.Color(204, 204, 255));
        rSButtonHover2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        rSButtonHover2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search member.png"))); // NOI18N
        rSButtonHover2.setColorHover(new java.awt.Color(255, 0, 153));
        rSButtonHover2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 50, 20));

        txtDiscription.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDiscription.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(txtDiscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 170, 110));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Description With");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 140, 30));

        endDate.setForeground(new java.awt.Color(102, 255, 0));
        endDate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 170, 30));

        startDate.setForeground(new java.awt.Color(102, 255, 0));
        startDate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 170, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Start Date");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("End Date");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fees Mode");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, 20));

        cmbxFeesmode.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cmbxFeesmode.setForeground(new java.awt.Color(0, 153, 51));
        cmbxFeesmode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Quartly" }));
        jPanel3.add(cmbxFeesmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 170, -1));

        txtAddress.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 170, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        txtOccupation.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtOccupation.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(txtOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 170, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Occupation");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, 30));

        registeredDate.setForeground(new java.awt.Color(102, 255, 0));
        registeredDate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(registeredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 170, 30));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("registered Date");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, 30));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NSBM Email");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 30));

        txtEmail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 153, 51));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 170, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Get Your ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ID");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 18, -1, 30));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(204, 0, 0));
        txtId.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtIdComponentShown(evt);
            }
        });
        txtId.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtIdInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 220, 30));

        rSButtonHover9.setBackground(new java.awt.Color(204, 204, 255));
        rSButtonHover9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        rSButtonHover9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search member.png"))); // NOI18N
        rSButtonHover9.setColorHover(new java.awt.Color(0, 153, 51));
        rSButtonHover9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rSButtonHover9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover9ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonHover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 80, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 450, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TollHome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, 50));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setBackground(new java.awt.Color(204, 0, 0));
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSave.setText("Save");
        btnSave.setColorHover(new java.awt.Color(0, 153, 51));
        btnSave.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, -1));

        rSButtonHover10.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonHover10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        rSButtonHover10.setText("Cancel");
        rSButtonHover10.setColorHover(new java.awt.Color(0, 153, 51));
        rSButtonHover10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonHover10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 390, 90));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("(University ID)");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 740, 550));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fill the Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPhoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, 160));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upload", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpload.setBackground(new java.awt.Color(102, 102, 255));
        btnUpload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnUpload.setText("Upload");
        btnUpload.setColorHover(new java.awt.Color(255, 0, 153));
        btnUpload.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 30));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 80));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1606197699786.png"))); // NOI18N
        jPanel4.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, 70));

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setText("NSBM ID");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Please Upload Your ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtmembernoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtmembernoComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtmembernoComponentShown

    private void txtIdComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtIdComponentShown
        // TODO add your handling code here:
        try{con=Connect.connectDb();
		
		String sql1="Select id from members";
		pst=con.prepareStatement(sql1);
		rs=pst.executeQuery();
		int a=0;
		while(rs.next())
		{
			a=rs.getInt("id");
		}
		a=a+1;
		String aa=String.valueOf(a);
		txtId.setText(aa);
		}catch(Exception e)
		{
			JOptionPane.showMessageDialog(null, e);
		}
        
    }//GEN-LAST:event_txtIdComponentShown

    private void dobMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dobMouseReleased

    private void dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyReleased
        // TODO add your handling code here:SimpleDateFormat format= new SimpleDateFormat("yyyy-MMMMMM-dd");
				SimpleDateFormat format= new SimpleDateFormat("yyyy-MMMMMM-dd");
				String s=format.format(dob.getDate());
				String arr[]=s.split("-");
				int year=Integer.parseInt(arr[0]);
				Month month=(Month.valueOf(arr[1].toUpperCase()));
				int day=Integer.parseInt(arr[2]);
				
				LocalDate localDate=LocalDate.now();
				LocalDate birthday=LocalDate.of(year, month, day);
				
				Period p=Period.between(birthday, localDate);
				int curAge=p.getYears();
				String curAge1=String.valueOf(curAge);
				
			
				
			
    }//GEN-LAST:event_dobKeyReleased

    private void txtFullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullnameKeyReleased
        // TODO add your handling code here:
        updatedMember=txtFullname.getText();
    }//GEN-LAST:event_txtFullnameKeyReleased

    private void cmbxDurationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxDurationItemStateChanged
        // TODO add your handling code here:
        String item=cmbxDuration.getSelectedItem().toString();
				if(item.equals("4"))
					{
					Date d=startDate.getDate();
					int month=d.getMonth();
					month=month+4;
					int day=d.getDay();
					day=day+4;
					d.setMonth(month);
					
					endDate.setDate(d);
					
					}
			
    }//GEN-LAST:event_cmbxDurationItemStateChanged

    private void txtmembernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmembernoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtmembernoActionPerformed

    private void rdbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnMaleActionPerformed
        // TODO add your handling code here:
        gender="Male";
    }//GEN-LAST:event_rdbtnMaleActionPerformed

    private void rdbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnFemaleActionPerformed
        // TODO add your handling code here:
        gender="Female";
    }//GEN-LAST:event_rdbtnFemaleActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtIdInputMethodTextChanged
        // TODO add your handling code here:   
    }//GEN-LAST:event_txtIdInputMethodTextChanged

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser imgchooser=new JFileChooser();
				imgchooser.showOpenDialog(null);
				File f= new File(imgchooser.getSelectedFile().getPath());
				filename=f.getAbsolutePath();
				ImageIcon myImage= new ImageIcon(filename);
				Image  img= myImage.getImage();
				Image newImage=img.getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(),Image.SCALE_SMOOTH);
				finalImage=new ImageIcon(newImage);
				lblPhoto.setIcon(finalImage);
    }//GEN-LAST:event_btnUploadActionPerformed

    private void rSButtonHover9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover9ActionPerformed
        try{con=Connect.connectDb();
		
		String sql1="Select id from members";
		pst=con.prepareStatement(sql1);
		rs=pst.executeQuery();
		int a=0;
		while(rs.next())
		{
			a=rs.getInt("id");
		}
		a=a+1;
		String aa=String.valueOf(a);
		txtId.setText(aa);
		}catch(Exception e)
		{
			JOptionPane.showMessageDialog(null, e);
		}
    }//GEN-LAST:event_rSButtonHover9ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
           try{con=Connect.connectDb();
		
		String sql1="Select membership_no from members";
		pst=con.prepareStatement(sql1);
		rs=pst.executeQuery();
		int a=0;
		while(rs.next())
		{
			a=rs.getInt("membership_no");
		}
		a=a+1;
		String aa=String.valueOf(a);
		txtmemberno.setText(aa);
		}catch(Exception e)
		{
			JOptionPane.showMessageDialog(null, e);
		}
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        con=Connect.connectDb();
				String sql=null;
				if(btnSave.getText().equals("Save"))
				{
				sql="Insert into members(membership_no,full_name,gender,address,country,weight,"+
				"status,email,reg_date,start_date,end_date,fees_mode,discription,duration,paid_fee,"+
				"contact_no,dob,occupation,img) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
				}
				else if(btnSave.getText().equals("Update"))
				{
				
					sql="update members set membership_no=?,full_name=?,gender=?,address=?,country=?,weight=?,"+ 
							"status=?,email=?,reg_date=?,start_date=?,end_date=?,fees_mode=?,discription=?,duration=?,paid_fee=?,"+ 
							"contact_no=?,dob=?,occupation=?,img=? where membership_no="+txtmemberno.getText()+"";
				}
				else {
					
				}
				try{
					pst = con.prepareStatement(sql);
					pst.setString (1,txtmemberno.getText());   
					pst.setString (2, txtFullname.getText());
					pst.setString (3,gender);
					pst.setString (4,txtAddress.getText());
					
					contryVal=comboCountry.getSelectedItem().toString();;
					pst.setString (5, contryVal);
					pst.setString (6, txtWeight.getText());
					
					String statusVal=cmbxStatus.getSelectedItem().toString();	
					pst.setString (7, statusVal);
					pst.setString (8, txtEmail.getText());
				
					pst.setString (9, ((JTextField)registeredDate.getDateEditor().getUiComponent()).getText());
					pst.setString (10, ((JTextField)startDate.getDateEditor().getUiComponent()).getText());
					pst.setString (11, ((JTextField)endDate.getDateEditor().getUiComponent()).getText());
					
					String feesModeVal=cmbxFeesmode.getSelectedItem().toString();				
					pst.setString (12, feesModeVal);

					pst.setString (13, txtDiscription.getText());
					
					String durationVal=cmbxDuration.getSelectedItem().toString();
					pst.setString(14, durationVal);
					pst.setString(15, txtPaidfee.getText());
					pst.setString(16, textContact.getText());
					pst.setString (17, ((JTextField)dob.getDateEditor().getUiComponent()).getText());
					pst.setString(18, txtOccupation.getText());
					
					if(filename!=null)
		            {
					FileInputStream fis=new FileInputStream(filename);
		            pst.setBinaryStream(19,fis,(int)filename.length());
					pst.execute();
					
					Date det=new Date();
					SimpleDateFormat format=new SimpleDateFormat("yyyy/MM/dd hh:mm:ss");
					String date=format.format(det);
					Login log=new Login();
					
					if(btnSave.getText().equals("Update"))
					{
						JOptionPane.showMessageDialog(null, "Data updated successfully");
						
						/* For Storing History in database*/
						String msz="Member "+txtFullname.getText()+" is updated to "+updatedMember+" by "+log.Hitory_User+"";
						String sql1="Insert into history(date,task) values(?,?)";
						pst=con.prepareStatement(sql1);
						pst.setString(1, date);
						pst.setString(2, msz);
						pst.execute();
					}
					else if(btnSave.getText().equals("Save"))
					{
					JOptionPane.showMessageDialog(null, "Data successfully inserted");
                                        txtId.setText(null);
                                        txtFullname.setText(null);
                                        txtmemberno.setText(null);
                                        textContact.setText(null);
                                        dob.setDate(null);   
                                        registeredDate.setDate(null);
                                        startDate.setDate(null);
                                        endDate.setDate(null);        
                                        txtWeight.setText(null);  
                                        txtPaidfee.setText(null);        
                                        txtEmail.setText(null);        
                                        txtOccupation.setText(null);        
                                        txtAddress.setText(null);
                                        txtDiscription.setText(null);        
                                                
                                                
                                                
                                        String msz="Member "+txtFullname.getText()+" is added by "+log.Hitory_User+"";
					String sql1="Insert into history(date,task) values(?,?)";
					pst=con.prepareStatement(sql1);
					pst.setString(1, date);
					pst.setString(2, msz);
					pst.execute();
					}
					else {
						
					}
		            }
					else {
						JOptionPane.showMessageDialog(null, "PleaseSelect the image");
					}
					
					
					
								
			     
			     }
			     catch(Exception e1)
			     {
			    	 JOptionPane.showMessageDialog(null, e1);
			     }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
         Main_Window ad= new Main_Window();
	ad.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        	try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private rojerusan.RSButtonHover btnSave;
    private rojerusan.RSButtonHover btnUpload;
    private javax.swing.JComboBox<String> cmbxDuration;
    private javax.swing.JComboBox<String> cmbxFeesmode;
    private javax.swing.JComboBox<String> cmbxStatus;
    private javax.swing.JComboBox<String> comboCountry;
    private com.toedter.calendar.JDateChooser dob;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private rojerusan.RSLabelImage lblPhoto;
    private rojerusan.RSButtonHover rSButtonHover10;
    private rojerusan.RSButtonHover rSButtonHover2;
    private rojerusan.RSButtonHover rSButtonHover9;
    private rojerusan.RSLabelImage rSLabelImage1;
    private javax.swing.JRadioButton rdbtnFemale;
    private javax.swing.JRadioButton rdbtnMale;
    private com.toedter.calendar.JDateChooser registeredDate;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JTextField textContact;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDiscription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtPaidfee;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtmemberno;
    // End of variables declaration//GEN-END:variables

    

   
}
