
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class Adjusting_Fee extends javax.swing.JFrame {
         Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
    
         
    public Adjusting_Fee() {
          initComponents();
    }
    
public void Get_Fee()
	{
	
		String sql="Select id as'ID',duration as'Duration(in month)',amount as 'Amount' from fees";
        try{
        	con=Connect.connectDb();
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            Fee_Table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally {
	    	   try {
	    		   pst.close();
	    		   rs.close();
	    		   con.close();
				
			} catch (Exception e2) {
				JOptionPane.showMessageDialog(null, e2);
			}
	       }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Fee_Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNewButton = new rojerusan.RSButtonHover();
        btnUpdate = new rojerusan.RSButtonHover();
        btnNewButton_1 = new rojerusan.RSButtonHover();
        btnRefresh = new rojerusan.RSButtonHover();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adjusting Fee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fee_Table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fee_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Duration(in month)", "Amount"
            }
        ));
        jScrollPane1.setViewportView(Fee_Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 860, 400));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewButton.setBackground(new java.awt.Color(255, 0, 0));
        btnNewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNewButton.setText("New");
        btnNewButton.setColorHover(new java.awt.Color(255, 0, 153));
        btnNewButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 0, 0));
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnUpdate.setText("Update");
        btnUpdate.setColorHover(new java.awt.Color(255, 0, 153));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 160, -1));

        btnNewButton_1.setBackground(new java.awt.Color(255, 0, 0));
        btnNewButton_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNewButton_1.setText("Update All");
        btnNewButton_1.setColorHover(new java.awt.Color(255, 0, 153));
        btnNewButton_1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNewButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 160, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 0, 0));
        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRefresh.setText("Refresh");
        btnRefresh.setColorHover(new java.awt.Color(255, 0, 153));
        btnRefresh.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 160, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TollHome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       Get_Fee();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButtonActionPerformed
        Update_Fee_Value uffv= new Update_Fee_Value();
       uffv.ForInsert();
       uffv.show();
       hide();
    }//GEN-LAST:event_btnNewButtonActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         int row=Fee_Table.getSelectedRow();
				if(row>0)
				{
					String table_click=Fee_Table.getModel().getValueAt(row,0).toString();
					Update_Fee_Value ufv= new Update_Fee_Value();
					ufv.updating_fees(table_click);
					ufv.show();
				}
				else {
					JOptionPane.showMessageDialog(Fee_Table, "     Please select a row");
				}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_1ActionPerformed
        Update_Overall_Fee update=new Update_Overall_Fee();
				update.show();
                                hide();
    }//GEN-LAST:event_btnNewButton_1ActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Main_Window ad= new Main_Window();
        ad.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       	try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adjusting_Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adjusting_Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adjusting_Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adjusting_Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
	 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adjusting_Fee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Fee_Table;
    private rojerusan.RSButtonHover btnNewButton;
    private rojerusan.RSButtonHover btnNewButton_1;
    private rojerusan.RSButtonHover btnRefresh;
    private rojerusan.RSButtonHover btnUpdate;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
