
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class Forgot extends javax.swing.JFrame {
         Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;

    /**
     * Creates new form Forgot
     */
    public Forgot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        txtSecurity = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        txtYourPass = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnSearch = new rojerusan.RSButtonHover();
        btnRetrive = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Your Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Type");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security Question");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Answer");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtUsername.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 250, -1));

        txtFullname.setEditable(false);
        txtFullname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 250, -1));

        type.setEditable(false);
        type.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 250, -1));

        txtSecurity.setEditable(false);
        txtSecurity.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSecurity.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(txtSecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 250, -1));

        txtAnswer.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(txtAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 250, -1));

        txtYourPass.setEditable(false);
        txtYourPass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtYourPass.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(txtYourPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TollHome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 50, 50));

        btnSearch.setBackground(new java.awt.Color(255, 102, 102));
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search member.png"))); // NOI18N
        btnSearch.setColorHover(new java.awt.Color(0, 153, 51));
        btnSearch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 40, 40));

        btnRetrive.setBackground(new java.awt.Color(102, 102, 255));
        btnRetrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRetrive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        btnRetrive.setColorHover(new java.awt.Color(255, 0, 153));
        btnRetrive.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRetrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetriveActionPerformed(evt);
            }
        });
        jPanel2.add(btnRetrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 40, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetriveActionPerformed
        con=Connect.connectDb();
        String usernames=txtUsername.getText();
        String sql="Select answer,password from signup where username='"+usernames+"'";

        String ans= txtAnswer.getText();

        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();

            rs.next();
            if(ans.equals(rs.getString("answer")))
            {
                txtYourPass.setText(rs.getString(2));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnRetriveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        con=Connect.connectDb();
        String usernames=txtUsername.getText();
        String sql="Select full_name,security_question,type from signup where username='"+usernames+"'";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {
                txtFullname.setText(rs.getString(1));
                txtSecurity.setText(rs.getString(2));
                type.setText(rs.getString(3));

            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Login ad= new Login();
        ad.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
           try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnRetrive;
    private rojerusan.RSButtonHover btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtSecurity;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtYourPass;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
