
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class History extends javax.swing.JFrame {
    Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;

    /**
     * Creates new form History
     */
         public void Get_History()
	{
		String sql="Select id as'ID',date as'Date and Time ',task as 'Task' from history";
        try{
        	con=Connect.connectDb();
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
         //   rs.next();
            History_Table.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
	}
    public History() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        History_Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnRefresh = new rojerusan.RSButtonHover();
        btnLatest = new rojerusan.RSButtonHover();
        btnClearAll = new rojerusan.RSButtonHover();
        btnClear = new rojerusan.RSButtonHover();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        History_Table.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        History_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Date and Time", "Task"
            }
        ));
        jScrollPane1.setViewportView(History_Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 940, 260));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefresh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRefresh.setText("Refresh");
        btnRefresh.setColorHover(new java.awt.Color(255, 0, 153));
        btnRefresh.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 160, 30));

        btnLatest.setBackground(new java.awt.Color(102, 102, 255));
        btnLatest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLatest.setText("Latest");
        btnLatest.setColorHover(new java.awt.Color(255, 0, 153));
        btnLatest.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLatest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLatestActionPerformed(evt);
            }
        });
        jPanel1.add(btnLatest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 30));

        btnClearAll.setBackground(new java.awt.Color(102, 102, 255));
        btnClearAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClearAll.setText("ClearAll");
        btnClearAll.setColorHover(new java.awt.Color(255, 0, 153));
        btnClearAll.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 160, 30));

        btnClear.setBackground(new java.awt.Color(102, 102, 255));
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnClear.setText("Clear");
        btnClear.setColorHover(new java.awt.Color(255, 0, 153));
        btnClear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 160, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TollHome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      Get_History();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnLatestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLatestActionPerformed
        try {
					con=Connect.connectDb();
					String sql="Select id as'ID',date as'Date',task as 'Task' from history order by id desc";
			       			        	con=Connect.connectDb();
			            pst=con.prepareStatement(sql);
			            rs=pst.executeQuery();
			         //   rs.next();
			            History_Table.setModel(DbUtils.resultSetToTableModel(rs));
			                  
					
				}catch(Exception e)
				{
					JOptionPane.showMessageDialog(null, e);
				}
			
    }//GEN-LAST:event_btnLatestActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        try {
					con=Connect.connectDb();
					String sql = "TRUNCATE history";
					pst=con.prepareStatement(sql);
					pst.executeUpdate(sql);
					
					if(pst.execute())
					{
						JOptionPane.showMessageDialog(History_Table, "Sorry history isnot cleared");
					}
					else
					{
						JOptionPane.showMessageDialog(History_Table, "All history is cleared");
					}
					
					
				}catch(Exception ee)
				{
					JOptionPane.showMessageDialog(null, ee);
				}
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        try {
					con=Connect.connectDb();
					int row= History_Table.getSelectedRow();
					if(row>0)
					{
						String table_click=History_Table.getModel().getValueAt(row,0).toString();
					
					String sql="Delete from history where id='"+table_click+"'";
					pst=con.prepareStatement(sql);
					if(pst.execute())
					{
						JOptionPane.showMessageDialog(History_Table, "Sorry history isnot cleared");
					}
					else
					{
						JOptionPane.showMessageDialog(History_Table, "Selected history is cleared");
					}
					}
					else {
						JOptionPane.showMessageDialog(History_Table, "Pleasse select any history");
						
						
					}
					
					
				}catch(Exception ee)
				{
					JOptionPane.showMessageDialog(null, ee);
				}
    }//GEN-LAST:event_btnClearActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Main_Window ad= new Main_Window();
        ad.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
            try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable History_Table;
    private rojerusan.RSButtonHover btnClear;
    private rojerusan.RSButtonHover btnClearAll;
    private rojerusan.RSButtonHover btnLatest;
    private rojerusan.RSButtonHover btnRefresh;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
