
import java.awt.EventQueue;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class Login extends javax.swing.JFrame {
    Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
         
       public String Hitory_User;
    
       
    public Login() {
        initComponents();
    }
    
    
public void loggedIn()
	{
		con=Connect.connectDb();
		String uname=txtUsername.getText();
		Hitory_User=txtUsername.getText();
		String pasw=String.valueOf(txtPassword.getPassword());
                
		String sql="Select * from signup where username='"+uname+"' and password='"+pasw+"'";
		
	     try{
	         pst=con.prepareStatement(sql);
	         rs=pst.executeQuery();
	          
		if(rs.next())
		{
			if(comboUserType.getSelectedItem().equals("admin"))
			{
			Date det=new Date();
			SimpleDateFormat format=new SimpleDateFormat("yyyy/MM/dd hh:mm:ss");
			String date=format.format(det);
			String msz="Logged in by "+Hitory_User;
			String sql1="Insert into history(date,task) values(?,?)";
			pst=con.prepareStatement(sql1);
			pst.setString(1, date);
			pst.setString(2, msz);
			pst.execute();
			rs.close();
			pst.close();
			
			Main_Window mnwd= new Main_Window();
			JOptionPane.showMessageDialog(null, "Login Successfully!!\nYou are Welcome in Our Gym Syemtem");
			hide();
			mnwd.show();
		}
			else {
				Date det=new Date();
				SimpleDateFormat format=new SimpleDateFormat("yyyy/MM/dd hh:mm:ss");
				String date=format.format(det);
				String msz="Logged in by "+Hitory_User;
				String sql1="Insert into history(date,task) values(?,?)";
				pst=con.prepareStatement(sql1);
				pst.setString(1, date);
				pst.setString(2, msz);
				pst.execute();
				rs.close();
				pst.close();
				
				User_Frame ufwd= new User_Frame();
				JOptionPane.showMessageDialog(null, "Login Successfully!!\nYou are Welcome in Our Gym Syemtem");
				hide();
				ufwd.show();
				
			}
		}

	else {
		JOptionPane.showMessageDialog(null, "Incorrect username and password!!!");
	}
	}catch(SQLException e)
	    
	     {
			JOptionPane.showMessageDialog(null, e);
	     }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboUserType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNewButton = new rojerusan.RSButtonHover();
        btnNewButton1 = new rojerusan.RSButtonHover();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 204, 0));
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });
        kGradientPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, -1));

        txtPassword.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 204, 0));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        kGradientPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 90, 20));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Type");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, 20));

        comboUserType.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        comboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "User" }));
        kGradientPanel1.add(comboUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 210, -1));

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText(" Gym Management System");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 380, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 20, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 20, 20));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNewButton.setBackground(new java.awt.Color(255, 0, 0));
        btnNewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNewButton.setText("Login");
        btnNewButton.setColorHover(new java.awt.Color(255, 0, 153));
        btnNewButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButtonActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 160, -1));

        btnNewButton1.setBackground(new java.awt.Color(255, 0, 0));
        btnNewButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNewButton1.setText("Signup");
        btnNewButton1.setColorHover(new java.awt.Color(255, 0, 153));
        btnNewButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 390, 80));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Forgot Password");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 10));

        jLabel8.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Welcome To NSBM");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 290, 30));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1606197699786.png"))); // NOI18N
        kGradientPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 60));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
       
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
       
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Forgot forgot= new Forgot();
	hide();
	forgot.show();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButtonActionPerformed
        loggedIn();  
    }//GEN-LAST:event_btnNewButtonActionPerformed

    private void btnNewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton1ActionPerformed
        SignUp sign= new SignUp();
				setVisible(false);
				sign.show();
                                hide();
    }//GEN-LAST:event_btnNewButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

		
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnNewButton;
    private rojerusan.RSButtonHover btnNewButton1;
    private javax.swing.JComboBox<String> comboUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
