
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class SignUp extends javax.swing.JFrame {
         Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtpasswordField = new javax.swing.JPasswordField();
        userType = new javax.swing.JComboBox<>();
        txtanswer = new javax.swing.JTextField();
        txtcomboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtfullname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnCreate = new rojerusan.RSButtonHover();
        btnNew = new rojerusan.RSButtonHover();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpasswordField.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtpasswordField.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(txtpasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 280, -1));

        userType.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        userType.setForeground(new java.awt.Color(255, 0, 0));
        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));
        jPanel2.add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 280, -1));

        txtanswer.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtanswer.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 280, -1));

        txtcomboBox.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtcomboBox.setForeground(new java.awt.Color(0, 204, 0));
        txtcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your father name?", "What is your born city?", "Who is your Best Actor?" }));
        jPanel2.add(txtcomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 280, 20));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Full Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security Question");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Answer");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Type");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtusername.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(0, 204, 0));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 280, -1));

        txtfullname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtfullname.setForeground(new java.awt.Color(0, 204, 0));
        jPanel2.add(txtfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 280, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create Here", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setBackground(new java.awt.Color(102, 102, 255));
        btnCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCreate.setText("Create");
        btnCreate.setColorHover(new java.awt.Color(255, 0, 153));
        btnCreate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel3.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 160, 30));

        btnNew.setBackground(new java.awt.Color(102, 102, 255));
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnNew.setText("Clear");
        btnNew.setColorHover(new java.awt.Color(255, 0, 153));
        btnNew.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 160, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 430, 80));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TollHome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtfullname.setText(null);
        txtusername.setText(null);
        txtpasswordField.setText(null);
        txtanswer.setText(null);     
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
					con=Connect.connectDb();
					String sql = " insert into signup (full_name,username,password, security_question, answer,type)"
								+ " values (?, ?, ?, ?, ?, ?)";

	      	 PreparedStatement preparedStmt = con.prepareStatement(sql);
                 preparedStmt.setString (1,txtfullname.getText());
		     preparedStmt.setString (2,txtusername.getText());   
		     preparedStmt.setString (3,txtpasswordField.getText());
		     preparedStmt.setString(4, (String)txtcomboBox.getSelectedItem());
			 preparedStmt.setString(5, txtanswer.getText());
                         preparedStmt.setString(6,userType.getSelectedItem().toString());
			 preparedStmt.execute();
		      JOptionPane.showMessageDialog(null, "you have successfully created new account");
		      preparedStmt.close();
		      con.close();
		      txtusername.setText(null);
		      txtpasswordField.setText(null);
		      txtfullname.setText(null);
		      txtanswer.setText(null);
                      userType.setSelectedItem(null);
		      
		    }
		    catch (Exception e)
		    {
		    	JOptionPane.showMessageDialog(null, e);
		    }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Login ad= new Login();
        ad.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnCreate;
    private rojerusan.RSButtonHover btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JComboBox<String> txtcomboBox;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JPasswordField txtpasswordField;
    private javax.swing.JTextField txtusername;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
