
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class Update_Fee_Value extends javax.swing.JFrame {
Connection con=null;
	 ResultSet rs=null;
	 PreparedStatement pst=null;
    /**
     * Creates new form Update_Fee_Value
     */
    public Update_Fee_Value() {
        initComponents();
    }
    
    
    
 public void updating_fees(String rowid)
	{
			con=Connect.connectDb();
		 String sql="select * from fees where id='"+rowid+"'";
	       try {
		    	pst=con.prepareStatement(sql);
		        rs=pst.executeQuery();
		        if(rs.next())
		        {
		        	txtFeeIDn.setText(rs.getString("id"));
		        	txtFeeIDn.setEnabled(false);
		        	txtDur.setText(rs.getString("duration"));
		        	txtDur.setEnabled(false);
		        	txtAmnt.setText(rs.getString("amount"));
		        }
		       
	       }catch(Exception e)
	       {
	    	  JOptionPane.showMessageDialog(null, e); 
	       }
	       finally {
	    	   try {
	    		   pst.close();
	    		   rs.close();
	    		   con.close();
				
			} catch (Exception e2) {
				JOptionPane.showMessageDialog(null, e2);
			}
	       }
	       
	
	       
	
        }
 public void ForInsert()
	{

		con=Connect.connectDb();
		 String sql1="select * from fees";
	       try {
		    	pst=con.prepareStatement(sql1);
		        rs=pst.executeQuery();
		        int ino=0;
		        int dur=0;
		        while(rs.next())
		        {
		        	ino=(rs.getInt("id"));
		        	dur=rs.getInt("duration");
		        }
		        pst.close();
		        rs.close();
		        con.close();
		        
		        txtFeeIDn.setText(String.valueOf(ino+1));
		    	txtFeeIDn.setEnabled(false);
	        	txtDur.setText(String.valueOf(dur+1));
	        	txtDur.setEnabled(false);
	       }catch(Exception e)
	       {
	    	  JOptionPane.showMessageDialog(null, e); 
	       }
	       finally {
	    	   try {
	    		   pst.close();
	    		   rs.close();
	    		   con.close();
				
			} catch (Exception e2) {
				JOptionPane.showMessageDialog(null, e2);
			}
	       }
        }
  
	       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAmnt = new javax.swing.JTextField();
        txtFeeIDn = new javax.swing.JTextField();
        txtDur = new javax.swing.JTextField();
        lblUpdatingFee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new rojerusan.RSButtonHover();
        btnRefresh = new rojerusan.RSButtonHover();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Fee");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adjust Fee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fee Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Duration");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txtAmnt.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtAmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmntActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, -1));

        txtFeeIDn.setEditable(false);
        txtFeeIDn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtFeeIDn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));

        txtDur.setEditable(false);
        txtDur.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jPanel1.add(txtDur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, -1));

        lblUpdatingFee.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblUpdatingFee.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdatingFee.setText("In Month");
        jPanel1.add(lblUpdatingFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(255, 0, 0));
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnUpdate.setText("Save");
        btnUpdate.setColorHover(new java.awt.Color(255, 0, 153));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 120, 30));

        btnRefresh.setBackground(new java.awt.Color(255, 0, 0));
        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnRefresh.setText("Clear");
        btnRefresh.setColorHover(new java.awt.Color(255, 0, 153));
        btnRefresh.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 390, 80));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TollHome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 230));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmntActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       txtFeeIDn.setText(null);
       txtDur.setText(null);        
       txtAmnt.setText(null);        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         try {
					con=Connect.connectDb();
				
						String sql=null;
						if(btnUpdate.getText().equals("Update")) 
						{
							sql="Update fees set amount="+txtAmnt.getText()+" where id="+txtFeeIDn.getText()+"";
							pst=con.prepareStatement(sql);
							if(pst.execute())
								{
									JOptionPane.showMessageDialog(null,"Sorry data canot be Updated");
								}
							else {
								JOptionPane.showMessageDialog(null, "Successfully Updated");
								}
							 pst.close();
				    		 con.close();
						}
						else if(btnUpdate.getText().equals("Save"))
							{
								sql="Insert into fees(duration,amount) values("+txtDur.getText()+","+txtAmnt.getText()+")";
								pst=con.prepareStatement(sql);
								if(pst.execute())
								{
									JOptionPane.showMessageDialog(null,"Sorry data canot be inserted");
								}
								else {
										JOptionPane.showMessageDialog(null, "Successfully inserted");
									}
							 pst.close();
				    		 con.close();
							}
						else
						{
							
						}
						
				}catch (Exception ee) {
					JOptionPane.showMessageDialog(null, ee);
				}
				finally {
			    	   try {
			    		   pst.close();
			    		   con.close();
			    		  
						
					} catch (Exception e2) {
						JOptionPane.showMessageDialog(null, e2);
					}
			       }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        Main_Window ad= new Main_Window();
        ad.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
   
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      	try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Fee_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Fee_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Fee_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Fee_Value.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Fee_Value().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnRefresh;
    private rojerusan.RSButtonHover btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUpdatingFee;
    private javax.swing.JTextField txtAmnt;
    private javax.swing.JTextField txtDur;
    private javax.swing.JTextField txtFeeIDn;
    // End of variables declaration//GEN-END:variables

    

   
}
